name: material_study_coach
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.3.0
  camera: ^0.11.0+2
  freezed_annotation: ^2.4.1
  google_generative_ai: ^0.4.7
  json_annotation: ^4.9.0
  flutter_dotenv: ^6.0.0
  google_mlkit_object_detection: ^0.14.0
  image: ^4.2.0
  image_picker: ^1.1.2
  drift: ^2.21.0
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  drift_dev: ^2.21.0

flutter:

  uses-material-design: true

  assets:
    - .env
